# Generated by Django 5.0.4 on 2024-10-21 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(max_length=256)),
                ('youtube', models.CharField(max_length=256)),
                ('facebook', models.CharField(max_length=256)),
                ('reception_time', models.CharField(max_length=256)),
                ('lunch', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'footer',
                'verbose_name_plural': 'footer',
                'db_table': 'footer',
            },
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=256)),
                ('main_img', models.FileField(upload_to='')),
                ('description', models.CharField(max_length=256)),
                ('duration', models.CharField(max_length=50, verbose_name='duration')),
                ('lesson_duration', models.CharField(max_length=50, verbose_name='lesson_duration')),
                ('lesson_days', models.CharField(max_length=256, verbose_name='day_lessons')),
                ('age_limit', models.CharField(max_length=100, verbose_name='age limit')),
                ('requirement', models.CharField(max_length=256)),
                ('about', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'main',
                'verbose_name_plural': 'mains',
                'db_table': 'main',
            },
        ),
        migrations.CreateModel(
            name='Purposes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'purpose',
                'verbose_name_plural': 'purpose',
                'db_table': 'purpose',
            },
        ),
        migrations.CreateModel(
            name='StartAppCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'startappcategory',
                'verbose_name_plural': 'startappcategories',
                'db_table': 'startappcategory',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256)),
                ('gender', models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=256)),
                ('date_birth', models.DateField()),
                ('address', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=256)),
                ('startap_name', models.CharField(max_length=256)),
                ('about_startapp', models.CharField(max_length=256)),
                ('about_team', models.CharField(max_length=256)),
                ('project_prototype', models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], max_length=256)),
                ('startap_image', models.FileField(upload_to='startap_image/%Y/%m')),
                ('presentation', models.FileField(upload_to='presentation/%Y/%m', validators=[django.core.validators.FileExtensionValidator(['pptx', 'pdf'])], verbose_name='presentation')),
                ('agree', models.BooleanField(default=False)),
                ('purpose', models.ManyToManyField(to='common.purposes')),
                ('category', models.ManyToManyField(null=True, to='common.startappcategory')),
            ],
            options={
                'verbose_name': 'form',
                'verbose_name_plural': 'forms',
                'db_table': 'form',
            },
        ),
    ]
