# Generated by Django 5.0.4 on 2024-10-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='category',
            field=models.ManyToManyField(to='common.startappcategory'),
        ),
    ]
